name: Refactor report
description: 코드 리팩토링
title: "[♻️Refactor] "
labels: "♻️ Refactor"
body:
  - type: textarea
    id: content
    attributes:
      label: "내용"
      value: |
        ## 📌 설명
        > 리팩토링할 부분과 목적을 간단히 작성해주세요.

        ## 🛠️ 구현 목록
        > ✅ 구체적으로 작성하기

        - [ ] 
    validations:
      required: true
