name: git push into another repo to deploy to vercel

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: creates output
        run: sh ./build.sh

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: output
          destination-github-username: rhdtls3562
          destination-repository-name: Coworkers
          user-email: ${{ secrets.EMAIL }}
          commit-message: ${{ github.event.head_commit.message }}
          target-branch: develop

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
